### PR TITLE
Image upload only when changed

### PR DESCRIPTION
**Pull request by ssaraswati**
Changes to improve image uploading.
- Only upload images that have changed by recording a file hash as the image comment
- Add image to attachments based markdown formatted image links

### CODE REVIEW

**Comment by simonstamm** [comment]
Hey @ssaraswati, awesome timing - exactly what I also wanted to implement right now. One suggestion though: Probably change regex from `r"!\[\w\*\]\((.*)\)"` to `r"!\[[\w\. ]*\]\((?!http|file)(.*)\)"` because a lot of people are naming their picture like the filename which includes a dot or add spaces in the title? In addition I excluded http(s) and file to exclude images referencing on external images like pipeline status image etc. Wdyt?

**Comment by ssaraswati** [comment]
@simonstamm Seems like a good improvement, have updated the regex to your version.

**Comment by simonstamm** [comment]
Hey @pawelsikora, what do you think about this PR? Can this be merged? :)

**Comment by pawelsikora** [comment]
> Hey @pawelsikora, what do you think about this PR? Can this be merged? :)

Hi,

PR looks fine, thanks for this improvement! 

I will have a look at it today and merge&release a new version into pip repo if no changes will be needed :)

**Comment by pawelsikora** [comment]
Already in main&rel_0.2.6 in one commit:

[c022db9f5f90c4815feb69c78c24e0ae36dae01b](https://github.com/pawelsikora/mkdocs-with-confluence/commit/c022db9f5f90c4815feb69c78c24e0ae36dae01b)

Package pushed into pip:
[https://pypi.org/project/mkdocs-with-confluence/0.2.6/](https://pypi.org/project/mkdocs-with-confluence/0.2.6/)

**Pull request merged**
