### PR TITLE
Upload attachements on post page to support other mkdocs plugins

### PR DESCRIPTION
**Pull request by ssaraswati**
Upload images from the on post page event instead of on markdown so that they can be accessed from the site directory instead of source directory.

This allows images generated from other plugins (e.g. https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin) to be uploaded to confluence as attachments. 

Additionally update the regex to not match file descriptions as part of the file name by excluding spaces and commas from the group.

### CODE REVIEW

**Comment by simonstamm** [comment]
Hi @ssaraswati,

is there a reason you removed the `-` from the regex? (`r"!\[[\w\. -]*\]` to `r"!\[[\w\. ]*\]`)

**Comment by ssaraswati** [comment]
> Hi @ssaraswati,
> 
> is there a reason you removed the `-` from the regex? (`r"!\[[\w\. -]*\]` to `r"!\[[\w\. ]*\]`)

I think I just missed that when updating from main

> Hi @ssaraswati,
> 
> is there a reason you removed the `-` from the regex? (`r"!\[[\w\. -]*\]` to `r"!\[[\w\. ]*\]`)

Was missed when updating from main, have restored it now

**Comment by pawelsikora** [comment]
> Hi @ssaraswati,
> 
> is there a reason you removed the `-` from the regex? (`r"!\[[\w\. -]*\]` to `r"!\[[\w\. ]*\]`)

@simonstamm  Thanks for spotting that and keeping an eye (had noticed this line as well when reading it on my phone, but I am pretty busy and slow in responses recently tbh... sry. Hope it will change sooner than later ;) )

@ssaraswati Nice, I like it - I will take a look at it during the incoming weekend and will merge it. Just note: 'attachments' instead of 'attachements' in a commit message. I will take a look if I would not like to break that changes into two (move upload to post / regex) and will get back to you when merging into main/releasing during the weekend.

**Review by pawelsikora — CHANGES_REQUESTED** [review]
'attachments' instead of 'attachements' in a commit message

**Comment by ssaraswati** [comment]
> @ssaraswati Nice, I like it - I will take a look at it during the incoming weekend and will merge it. Just note: 'attachments' instead of 'attachements' in a commit message. I will take a look if I would not like to break that changes into two (move upload to post / regex) and will get back to you when merging into main/releasing during the weekend.

Have updated to fix the spelling issues on commit msg

**Review by pasikora — APPROVED** [review]

**Review by pawelsikora — APPROVED** [review]

**Pull request merged**
